name: Build Android Staging Release
# This workflow is triggered on pushes to the repository.
# see https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
on:
  push:
    tags:
      - '[0-9]*.[0-9]*.[0-9]*'

jobs:
  build:
    # Job name is Greeting
    name: Build Android Staging Release
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Start workflow
        run: echo workflow started

      - name: echo tag name
        run: echo ${GITHUB_REF/refs\/tags\//}

      - name: notify automated tests project
        run: |
          curl -X POST https://api.github.com/repos/OthmanK24/K24AutoTestsDemo/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "run-automated-tests", "client_payload": { "apklink": "some link" }}'

      - name: End workflow
        run: echo workflow ended