name: Build APK and dispatch to QA
# This workflow is triggered on push of tags with format X.Y.Z
# Which should build the apk and send a dispatch event to automated qa to run the action

on:
  push:
    tags:
      - '[0-9]*.[0-9]*.[0-9]*'

jobs:
  build:

    name: Build APK and dispatch to QA

    runs-on: ubuntu-latest
    steps:
      - name: Start workflow
        run: echo "workflow started"

      - name: echo tag name
        run: echo ${GITHUB_REF/refs\/tags\//}

      - name: build apk
        run: echo "...... build apk ......"

      - name: notify automated tests project
        run: |
          curl -X POST https://api.github.com/repos/OthmanK24/K24AutoTestsDemo/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "run-automated-tests", "client_payload": { "apklink": "some link" }}'

      - name: End workflow
        run: echo "workflow ended"